### ISSUE TITLE
FastAPI

### ISSUE THREAD

**Issue by arpeggi-15** [arpeggi-15/Flight-Fare-Prediction#1]
The backend of the model is based on Flask framework but FastAPI is a better python framework for backend.
SO, create a FastAPI backend for the prediction model

**Comment by Viveksati5143** [comment]
please assign me this issue

**Comment by PalaVenkiReddy** [comment]
Bhaiya, please assign this issue to me under JWOC.

**Comment by arpeggi-15** [comment]
> Bhaiya, please assign this issue to me under JWOC.

Assigned you the issue. Create a FastAPI for the model. Feel free to ask for any queries.

**Comment by PalaVenkiReddy** [comment]
Should I Modify app.py or create another file main.py for fastapi ?
