### ISSUE TITLE
Update Static Files.

### ISSUE THREAD

**Issue by arpeggi-15** [arpeggi-15/Flight-Fare-Prediction#9]
some styling is needed for input boxes of source, destination, name of airline, and number of stops as they are not properly aligned as we can see in the figure below. Can I solve this issue?

Style the input boxes and you can also do changes on the ui/ux for better user experience and can add more styling.

**Comment by ayushanand308** [comment]
Assign me this issue under JWOC @arpeggi-15. This will also solve the issue of a good landing page.

**Comment by ayushanand308** [comment]
[screen-capture (1).webm](https://user-images.githubusercontent.com/99035102/219566378-ce77e269-08aa-40ab-bf03-eace824e652d.webm)

**Comment by ayushanand308** [comment]
This is how I am thinking of executing this. Do you want to add something?

**Comment by ayushanand308** [comment]
@arpeggi-15  Should I go with It?

**Comment by arpeggi-15** [comment]
> This is how I am thinking of executing this. Do you want to add something?

Can you make the {{prediction_text}} look better?

**Comment by ayushanand308** [comment]
Will do.

**Comment by ayushanand308** [comment]
@arpeggi-15  Made a PR after changing the "prediction_text" part. Please review it.
